### LibROV

menuconfig:
	python $(FINNAV_ROOT_DIR)/Toolchain/kconfig-python/kconfig/kconfig.py

genconfig:
	python $(FINNAV_ROOT_DIR)/Toolchain/kconfig-python/kconfig/kconfig.py genconfig

defconfig:
	python $(FINNAV_ROOT_DIR)/Toolchain/kconfig-python/kconfig/kconfig.py defconfig

allyesconfig:
	python $(FINNAV_ROOT_DIR)/Toolchain/kconfig-python/kconfig/kconfig.py allyesconfig

allnoconfig:
	python $(FINNAV_ROOT_DIR)/Toolchain/kconfig-python/kconfig/kconfig.py allnoconfig

.PHONY = menuconfig genconfig defconfig allyesconfig allnoconfig
# *** EOF ***
